name: fff_dart
description: Dart bindings for the FFF C ABI.
version: 0.0.1
repository: https://github.com/elias8/fff_dart

platforms:
  android:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.13.4

dependencies:
  code_assets: ^2.1.0
  crypto: ^3.0.7
  hooks: ^2.2.0

dev_dependencies:
  ffigen: ^22.0.0
  lints: ^6.0.0
  logging: ^1.3.0
  test: ^1.31.1
