// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:fff_dart/fff_dart.dart')
library;

import 'dart:ffi' as ffi;

/// Create a new file finder instance (legacy 8-arg positional signature).
///
/// @deprecated Use [`fff_create_instance_with`] (or [`fff_create_instance_with_value`]
/// for FFI bindings). The `use_unsafe_no_lock` parameter is ignored.
///
/// ## Safety
/// See `fff_create_instance_with`.
@Deprecated(
  'Use fff_create_instance_with (by pointer) or fff_create_instance_with_value (by value) with FffCreateOptions instead. The struct evolves without ABI breaks.',
)
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Bool,
    ffi.Bool,
    ffi.Bool,
    ffi.Bool,
    ffi.Bool,
  )
>()
external ffi.Pointer<FffResult> fff_create_instance(
  ffi.Pointer<ffi.Char> base_path,
  ffi.Pointer<ffi.Char> frecency_db_path,
  ffi.Pointer<ffi.Char> history_db_path,
  bool _use_unsafe_no_lock,
  bool enable_mmap_cache,
  bool enable_content_indexing,
  bool watch,
  bool ai_mode,
);

/// Create a new file finder instance (legacy 13-arg positional signature).
///
/// @deprecated Use [`fff_create_instance_with`] (or [`fff_create_instance_with_value`]
/// for FFI bindings). The `use_unsafe_no_lock` parameter is ignored.
///
/// ## Safety
/// See `fff_create_instance_with`.
@Deprecated(
  'Use fff_create_instance_with (by pointer) or fff_create_instance_with_value (by value) with FffCreateOptions instead. The struct evolves without ABI breaks.',
)
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Bool,
    ffi.Bool,
    ffi.Bool,
    ffi.Bool,
    ffi.Bool,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external ffi.Pointer<FffResult> fff_create_instance2(
  ffi.Pointer<ffi.Char> base_path,
  ffi.Pointer<ffi.Char> frecency_db_path,
  ffi.Pointer<ffi.Char> history_db_path,
  bool _use_unsafe_no_lock,
  bool enable_mmap_cache,
  bool enable_content_indexing,
  bool watch,
  bool ai_mode,
  ffi.Pointer<ffi.Char> log_file_path,
  ffi.Pointer<ffi.Char> log_level,
  int cache_budget_max_files,
  int cache_budget_max_bytes,
  int cache_budget_max_file_size,
);

/// Create a new file finder instance from a versioned [`FffCreateOptions`] struct.
///
/// Populate the struct, set `version` to [`FFF_CREATE_OPTIONS_VERSION`], pass by
/// pointer. New fields are only appended; older `version` values keep working.
/// FFI bindings needing struct-by-value should use [`fff_create_instance_with_value`].
///
/// `opts.base_path` is required (non-NULL, non-empty). Zero `cache_budget_*`
/// values are auto-computed from repo size after the initial scan.
///
/// ## Safety
/// * `opts` must be a valid pointer to an `FffCreateOptions` whose `version`
/// is in the range `1..=FFF_CREATE_OPTIONS_VERSION`.
/// * All string pointers inside `opts` must be valid null-terminated UTF-8
/// or NULL.
@ffi.Native<ffi.Pointer<FffResult> Function(ffi.Pointer<FffCreateOptions>)>()
external ffi.Pointer<FffResult> fff_create_instance_with(
  ffi.Pointer<FffCreateOptions> opts,
);

/// [`fff_create_instance_with`] adapter taking [`FffCreateOptions`] **by value**,
/// for FFI libraries that pass native structs by value (e.g. Node's `ffi-rs`).
///
/// ## Safety
/// All `*const c_char` fields inside `opts` must be valid null-terminated
/// UTF-8 or NULL. The struct itself is consumed by value.
@ffi.Native<ffi.Pointer<FffResult> Function(FffCreateOptions)>()
external ffi.Pointer<FffResult> fff_create_instance_with_value(
  FffCreateOptions opts,
);

/// Destroy a file finder instance and free all its resources.
///
/// ## Safety
/// `fff_handle` must be a valid pointer returned by `fff_create_instance`, or null (no-op).
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void fff_destroy(ffi.Pointer<ffi.Void> fff_handle);

/// Get a pointer to the `index`-th `FffDirItem` in a directory search result.
///
/// ## Safety
/// `result` must be a valid `FffDirSearchResult` pointer from `fff_search_directories`.
@ffi.Native<
  ffi.Pointer<FffDirItem> Function(ffi.Pointer<FffDirSearchResult>, ffi.Uint32)
>()
external ffi.Pointer<FffDirItem> fff_dir_search_result_get_item(
  ffi.Pointer<FffDirSearchResult> result,
  int index,
);

/// Get a pointer to the `index`-th `FffScore` in a directory search result.
///
/// ## Safety
/// `result` must be a valid `FffDirSearchResult` pointer from `fff_search_directories`.
@ffi.Native<
  ffi.Pointer<FffScore> Function(ffi.Pointer<FffDirSearchResult>, ffi.Uint32)
>()
external ffi.Pointer<FffScore> fff_dir_search_result_get_score(
  ffi.Pointer<FffDirSearchResult> result,
  int index,
);

/// Access-based frecency score; `0` if `item` is null.
///
/// ## Safety
/// `item` must be a valid `FffFileItem` pointer or null.
@ffi.Native<ffi.Int64 Function(ffi.Pointer<FffFileItem>)>()
external int fff_file_item_get_access_frecency_score(
  ffi.Pointer<FffFileItem> item,
);

/// File-name component of a file item (e.g. `"main.rs"`); null if `item` is null. Do not free.
///
/// ## Safety
/// `item` must be a valid `FffFileItem` pointer or null.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffFileItem>)>()
external ffi.Pointer<ffi.Char> fff_file_item_get_file_name(
  ffi.Pointer<FffFileItem> item,
);

/// Git status string of a file item (e.g. `"M "`, `"??"`); null if git is unavailable,
/// the file is untracked, or `item` is null. Do not free.
///
/// ## Safety
/// `item` must be a valid `FffFileItem` pointer or null.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffFileItem>)>()
external ffi.Pointer<ffi.Char> fff_file_item_get_git_status(
  ffi.Pointer<FffFileItem> item,
);

/// `true` if the file was detected as binary; `false` if `item` is null.
///
/// ## Safety
/// `item` must be a valid `FffFileItem` pointer or null.
@ffi.Native<ffi.Bool Function(ffi.Pointer<FffFileItem>)>()
external bool fff_file_item_get_is_binary(ffi.Pointer<FffFileItem> item);

/// Modification-based frecency score; `0` if `item` is null.
///
/// ## Safety
/// `item` must be a valid `FffFileItem` pointer or null.
@ffi.Native<ffi.Int64 Function(ffi.Pointer<FffFileItem>)>()
external int fff_file_item_get_modification_frecency_score(
  ffi.Pointer<FffFileItem> item,
);

/// Last-modified time as seconds since the UNIX epoch; `0` if `item` is null.
///
/// ## Safety
/// `item` must be a valid `FffFileItem` pointer or null.
@ffi.Native<ffi.Uint64 Function(ffi.Pointer<FffFileItem>)>()
external int fff_file_item_get_modified(ffi.Pointer<FffFileItem> item);

/// Relative path of a file item (e.g. `"src/main.rs"`); null if `item` is null. Do not free.
///
/// ## Safety
/// `item` must be a valid `FffFileItem` pointer or null.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffFileItem>)>()
external ffi.Pointer<ffi.Char> fff_file_item_get_relative_path(
  ffi.Pointer<FffFileItem> item,
);

/// File size in bytes; `0` if `item` is null.
///
/// ## Safety
/// `item` must be a valid `FffFileItem` pointer or null.
@ffi.Native<ffi.Uint64 Function(ffi.Pointer<FffFileItem>)>()
external int fff_file_item_get_size(ffi.Pointer<FffFileItem> item);

/// Combined frecency score; `0` if `item` is null.
///
/// ## Safety
/// `item` must be a valid `FffFileItem` pointer or null.
@ffi.Native<ffi.Int64 Function(ffi.Pointer<FffFileItem>)>()
external int fff_file_item_get_total_frecency_score(
  ffi.Pointer<FffFileItem> item,
);

/// Free a directory search result returned by `fff_search_directories`.
///
/// ## Safety
/// `result` must be a valid pointer previously returned via `FffResult.handle`
/// from `fff_search_directories`, or null (no-op).
@ffi.Native<ffi.Void Function(ffi.Pointer<FffDirSearchResult>)>()
external void fff_free_dir_search_result(
  ffi.Pointer<FffDirSearchResult> result,
);

/// Free a grep result returned by `fff_live_grep` or `fff_multi_grep`:
/// the struct, its `items` array, and all strings/ranges/context within.
///
/// ## Safety
/// `result` must be a valid pointer previously returned via `FffResult.handle`
/// from `fff_live_grep` or `fff_multi_grep`, or null (no-op).
@ffi.Native<ffi.Void Function(ffi.Pointer<FffGrepResult>)>()
external void fff_free_grep_result(ffi.Pointer<FffGrepResult> result);

/// Free a mixed search result returned by `fff_search_mixed`.
///
/// ## Safety
/// `result` must be a valid pointer previously returned via `FffResult.handle`
/// from `fff_search_mixed`, or null (no-op).
@ffi.Native<ffi.Void Function(ffi.Pointer<FffMixedSearchResult>)>()
external void fff_free_mixed_search_result(
  ffi.Pointer<FffMixedSearchResult> result,
);

/// Free a result envelope returned by any `fff_*` function.
/// **IMPORTANT:** the `handle` payload is NOT freed release it separately
/// using handle specific cleaning methods (`fff_destroy`, `fff_free_search_result`, etc.).
///
/// ## Safety
/// `result_ptr` must be a valid pointer returned by a `fff_*` function.
@ffi.Native<ffi.Void Function(ffi.Pointer<FffResult>)>()
external void fff_free_result(ffi.Pointer<FffResult> result_ptr);

/// Free a scan progress result returned by `fff_get_scan_progress`.
///
/// ## Safety
/// `result` must be a valid pointer previously returned via `FffResult.handle`
/// from `fff_get_scan_progress`, or null (no-op).
@ffi.Native<ffi.Void Function(ffi.Pointer<FffScanProgress>)>()
external void fff_free_scan_progress(ffi.Pointer<FffScanProgress> result);

/// Free a search result returned by `fff_search`: the struct, its `items`
/// and `scores` arrays, and every string within.
///
/// ## Safety
/// `result` must be a valid pointer previously returned via `FffResult.handle`
/// from `fff_search`, or null (no-op).
@ffi.Native<ffi.Void Function(ffi.Pointer<FffSearchResult>)>()
external void fff_free_search_result(ffi.Pointer<FffSearchResult> result);

/// Free a string returned by `fff_*` functions.
///
/// ## Safety
/// `s` must be a valid C string allocated by this library.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void fff_free_string(ffi.Pointer<ffi.Char> s);

/// Free a watch event batch delivered to the instance callback.
///
/// ## Safety
/// `batch` must be a pointer produced by this library, or null (no-op).
@ffi.Native<ffi.Void Function(ffi.Pointer<FffWatchEventBatch>)>()
external void fff_free_watch_events(ffi.Pointer<FffWatchEventBatch> batch);

/// Get the picker's base path as a heap C string in `handle`;
/// free it with `fff_free_string`.
///
/// ## Safety
/// `fff_handle` must be a valid instance pointer from `fff_create_instance`.
@ffi.Native<ffi.Pointer<FffResult> Function(ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<FffResult> fff_get_base_path(
  ffi.Pointer<ffi.Void> fff_handle,
);

/// Get historical query by offset (0 = most recent).
///
/// ## Safety
/// `fff_handle` must be a valid instance pointer from `fff_create_instance`.
@ffi.Native<
  ffi.Pointer<FffResult> Function(ffi.Pointer<ffi.Void>, ffi.Uint64)
>()
external ffi.Pointer<FffResult> fff_get_historical_query(
  ffi.Pointer<ffi.Void> fff_handle,
  int offset,
);

/// Get scan progress information.
///
/// ## Safety
/// `fff_handle` must be a valid instance pointer from `fff_create_instance`.
@ffi.Native<ffi.Pointer<FffResult> Function(ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<FffResult> fff_get_scan_progress(
  ffi.Pointer<ffi.Void> fff_handle,
);

/// Glob-only search: filter indexed files by a single glob pattern (passed
/// through verbatim, no query parsing), rank by frecency, and paginate.
///
/// `current_file` deprioritizes the currently open file (NULL/empty to skip).
/// Zero picks the default: `max_threads` auto, `page_size` 100.
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`.
/// * `pattern` and `current_file` must be valid null-terminated UTF-8 strings or NULL.
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external ffi.Pointer<FffResult> fff_glob(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> pattern,
  ffi.Pointer<ffi.Char> current_file,
  int max_threads,
  int page_index,
  int page_size,
);

/// Access-based frecency score of the matched file; `0` if `m` is null.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Int64 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_access_frecency_score(
  ffi.Pointer<FffGrepMatch> m,
);

/// Byte offset of the match start from the beginning of the file; `0` if `m` is null.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Uint64 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_byte_offset(ffi.Pointer<FffGrepMatch> m);

/// 0-based column of the match start within its line; `0` if `m` is null.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_col(ffi.Pointer<FffGrepMatch> m);

/// The `index`-th context line after the match; null if `m` is null,
/// `index >= context_after_count`, or the context array is null. Do not free.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffGrepMatch>, ffi.Uint32)
>()
external ffi.Pointer<ffi.Char> fff_grep_match_get_context_after(
  ffi.Pointer<FffGrepMatch> m,
  int index,
);

/// Number of context lines captured after the match; `0` if `m` is null.
/// Use with [`fff_grep_match_get_context_after`] to read each line.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_context_after_count(
  ffi.Pointer<FffGrepMatch> m,
);

/// The `index`-th context line before the match; null if `m` is null,
/// `index >= context_before_count`, or the context array is null. Do not free.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffGrepMatch>, ffi.Uint32)
>()
external ffi.Pointer<ffi.Char> fff_grep_match_get_context_before(
  ffi.Pointer<FffGrepMatch> m,
  int index,
);

/// Number of context lines captured before the match; `0` if `m` is null.
/// Use with [`fff_grep_match_get_context_before`] to read each line.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_context_before_count(
  ffi.Pointer<FffGrepMatch> m,
);

/// File-name component of the file containing this grep match; null if `m` is null. Do not free.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffGrepMatch>)>()
external ffi.Pointer<ffi.Char> fff_grep_match_get_file_name(
  ffi.Pointer<FffGrepMatch> m,
);

/// Fuzzy match score; `0` if `m` is null or no fuzzy score is present.
/// Always check [`fff_grep_match_get_has_fuzzy_score`] first; `0` is ambiguous without that flag.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Uint16 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_fuzzy_score(ffi.Pointer<FffGrepMatch> m);

/// Git status string of the matched file (e.g. `"M "`, `"??"`); null if git is unavailable,
/// the file is untracked, or `m` is null. Do not free.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffGrepMatch>)>()
external ffi.Pointer<ffi.Char> fff_grep_match_get_git_status(
  ffi.Pointer<FffGrepMatch> m,
);

/// `true` if this match carries a valid fuzzy score; `false` if `m` is null.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Bool Function(ffi.Pointer<FffGrepMatch>)>()
external bool fff_grep_match_get_has_fuzzy_score(ffi.Pointer<FffGrepMatch> m);

/// `true` if the matched file was detected as binary; `false` if `m` is null.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Bool Function(ffi.Pointer<FffGrepMatch>)>()
external bool fff_grep_match_get_is_binary(ffi.Pointer<FffGrepMatch> m);

/// `true` if the match was identified as a symbol definition; `false` if `m` is null.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Bool Function(ffi.Pointer<FffGrepMatch>)>()
external bool fff_grep_match_get_is_definition(ffi.Pointer<FffGrepMatch> m);

/// Full text content of the matched line; null if `m` is null. Do not free.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffGrepMatch>)>()
external ffi.Pointer<ffi.Char> fff_grep_match_get_line_content(
  ffi.Pointer<FffGrepMatch> m,
);

/// 1-based line number of the match within its file; `0` if `m` is null.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Uint64 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_line_number(ffi.Pointer<FffGrepMatch> m);

/// Pointer to the `index`-th [`FffMatchRange`] highlight span; null if `m` is null,
/// `index >= match_ranges_count`, or the ranges array is null. Valid until the owning `FffGrepResult` is freed; do not free.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<
  ffi.Pointer<FffMatchRange> Function(ffi.Pointer<FffGrepMatch>, ffi.Uint32)
>()
external ffi.Pointer<FffMatchRange> fff_grep_match_get_match_range(
  ffi.Pointer<FffGrepMatch> m,
  int index,
);

/// Number of highlight ranges in this match; `0` if `m` is null.
/// Use with [`fff_grep_match_get_match_range`] to iterate the highlight spans.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_match_ranges_count(ffi.Pointer<FffGrepMatch> m);

/// Modification-based frecency score of the matched file; `0` if `m` is null.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Int64 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_modification_frecency_score(
  ffi.Pointer<FffGrepMatch> m,
);

/// Last-modified time of the matched file as seconds since the UNIX epoch; `0` if `m` is null.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Uint64 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_modified(ffi.Pointer<FffGrepMatch> m);

/// Relative path of the file containing this grep match; null if `m` is null. Do not free.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffGrepMatch>)>()
external ffi.Pointer<ffi.Char> fff_grep_match_get_relative_path(
  ffi.Pointer<FffGrepMatch> m,
);

/// File size in bytes of the matched file; `0` if `m` is null.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Uint64 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_size(ffi.Pointer<FffGrepMatch> m);

/// Combined frecency score of the matched file; `0` if `m` is null.
///
/// ## Safety
/// `m` must be a valid `FffGrepMatch` pointer or null.
@ffi.Native<ffi.Int64 Function(ffi.Pointer<FffGrepMatch>)>()
external int fff_grep_match_get_total_frecency_score(
  ffi.Pointer<FffGrepMatch> m,
);

/// Number of matches in the result; `0` if `r` is null.
///
/// ## Safety
/// `r` must be a valid `FffGrepResult` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffGrepResult>)>()
external int fff_grep_result_get_count(ffi.Pointer<FffGrepResult> r);

/// Number of files eligible for search after path/type filtering; `0` if `r` is null.
///
/// ## Safety
/// `r` must be a valid `FffGrepResult` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffGrepResult>)>()
external int fff_grep_result_get_filtered_file_count(
  ffi.Pointer<FffGrepResult> r,
);

/// Pointer to the `index`-th `FffGrepMatch`; null if `result` is null or
/// `index >= count`. Valid until the grep result is freed.
///
/// ## Safety
/// `result` must be a valid `FffGrepResult` pointer from `fff_live_grep` or `fff_multi_grep`.
@ffi.Native<
  ffi.Pointer<FffGrepMatch> Function(ffi.Pointer<FffGrepResult>, ffi.Uint32)
>()
external ffi.Pointer<FffGrepMatch> fff_grep_result_get_match(
  ffi.Pointer<FffGrepResult> result,
  int index,
);

/// File offset for the next page; `0` if all files have been searched or `r` is null.
/// Pass as `file_offset` to a subsequent `fff_live_grep`/`fff_multi_grep` call to continue pagination.
///
/// ## Safety
/// `r` must be a valid `FffGrepResult` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffGrepResult>)>()
external int fff_grep_result_get_next_file_offset(ffi.Pointer<FffGrepResult> r);

/// Regex compilation error string if the engine fell back to literal matching;
/// null if there was no error or `r` is null. Do not free.
///
/// ## Safety
/// `r` must be a valid `FffGrepResult` pointer or null.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffGrepResult>)>()
external ffi.Pointer<ffi.Char> fff_grep_result_get_regex_fallback_error(
  ffi.Pointer<FffGrepResult> r,
);

/// Total number of indexed files before any filtering; `0` if `r` is null.
///
/// ## Safety
/// `r` must be a valid `FffGrepResult` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffGrepResult>)>()
external int fff_grep_result_get_total_files(ffi.Pointer<FffGrepResult> r);

/// Number of files actually opened and searched in this call; `0` if `r` is null.
///
/// ## Safety
/// `r` must be a valid `FffGrepResult` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffGrepResult>)>()
external int fff_grep_result_get_total_files_searched(
  ffi.Pointer<FffGrepResult> r,
);

/// Total number of matches found across all pages; `0` if `r` is null.
///
/// ## Safety
/// `r` must be a valid `FffGrepResult` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffGrepResult>)>()
external int fff_grep_result_get_total_matched(ffi.Pointer<FffGrepResult> r);

/// Get health check information.
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`, or null for
/// a limited health check (version + git only).
/// * `test_path` can be null or a valid null-terminated UTF-8 string.
@ffi.Native<
  ffi.Pointer<FffResult> Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<FffResult> fff_health_check(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> test_path,
);

/// Check if a scan is currently in progress.
///
/// ## Safety
/// `fff_handle` must be a valid instance pointer from `fff_create_instance`.
@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>)>()
external bool fff_is_scanning(ffi.Pointer<ffi.Void> fff_handle);

/// Perform content search (grep) across indexed files.
///
/// `query` supports constraint syntax like `*.rs pattern`; `mode` is
/// 0 = plain text (SIMD), 1 = regex, 2 = fuzzy. Zero picks the default:
/// `max_file_size` 10 MB, `page_limit` 50, `max_matches_per_file` and
/// `time_budget_ms` unlimited. `smart_case` is case-insensitive for
/// all-lowercase queries; `classify_definitions` tags code definitions.
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`.
/// * `query` must be a valid null-terminated UTF-8 string.
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint8,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Bool,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Bool,
  )
>()
external ffi.Pointer<FffResult> fff_live_grep(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> query,
  int mode,
  int max_file_size,
  int max_matches_per_file,
  bool smart_case,
  int file_offset,
  int page_limit,
  int time_budget_ms,
  int before_context,
  int after_context,
  bool classify_definitions,
);

/// [`fff_live_grep`] plus `enforce_time_budget`: when true the budget also bounds
/// zero-match searches and `next_file_offset` resumes at the first unsearched file.
///
/// ## Safety
/// Same as [`fff_live_grep`].
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint8,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Bool,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint64,
    ffi.Bool,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Bool,
  )
>()
external ffi.Pointer<FffResult> fff_live_grep_ex(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> query,
  int mode,
  int max_file_size,
  int max_matches_per_file,
  bool smart_case,
  int file_offset,
  int page_limit,
  int time_budget_ms,
  bool enforce_time_budget,
  int before_context,
  int after_context,
  bool classify_definitions,
);

/// Get a pointer to the `index`-th `FffMixedItem` in a mixed search result.
///
/// ## Safety
/// `result` must be a valid `FffMixedSearchResult` pointer from `fff_search_mixed`.
@ffi.Native<
  ffi.Pointer<FffMixedItem> Function(
    ffi.Pointer<FffMixedSearchResult>,
    ffi.Uint32,
  )
>()
external ffi.Pointer<FffMixedItem> fff_mixed_search_result_get_item(
  ffi.Pointer<FffMixedSearchResult> result,
  int index,
);

/// Get a pointer to the `index`-th `FffScore` in a mixed search result.
///
/// ## Safety
/// `result` must be a valid `FffMixedSearchResult` pointer from `fff_search_mixed`.
@ffi.Native<
  ffi.Pointer<FffScore> Function(ffi.Pointer<FffMixedSearchResult>, ffi.Uint32)
>()
external ffi.Pointer<FffScore> fff_mixed_search_result_get_score(
  ffi.Pointer<FffMixedSearchResult> result,
  int index,
);

/// Multi-pattern OR search (SIMD Aho-Corasick): lines matching ANY pattern.
///
/// `patterns_joined` is `\n`-separated (e.g. `"foo\nbar"`); `constraints` is an
/// optional file filter like `"*.rs"` or `"/src/"` (NULL/empty to skip).
/// Remaining parameters as in [`fff_live_grep`].
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`.
/// * `patterns_joined` and `constraints` must be valid null-terminated UTF-8 or NULL.
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Bool,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Bool,
  )
>()
external ffi.Pointer<FffResult> fff_multi_grep(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> patterns_joined,
  ffi.Pointer<ffi.Char> constraints,
  int max_file_size,
  int max_matches_per_file,
  bool smart_case,
  int file_offset,
  int page_limit,
  int time_budget_ms,
  int before_context,
  int after_context,
  bool classify_definitions,
);

/// [`fff_multi_grep`] plus `enforce_time_budget`, as in [`fff_live_grep_ex`].
///
/// ## Safety
/// Same as [`fff_multi_grep`].
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Bool,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint64,
    ffi.Bool,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Bool,
  )
>()
external ffi.Pointer<FffResult> fff_multi_grep_ex(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> patterns_joined,
  ffi.Pointer<ffi.Char> constraints,
  int max_file_size,
  int max_matches_per_file,
  bool smart_case,
  int file_offset,
  int page_limit,
  int time_budget_ms,
  bool enforce_time_budget,
  int before_context,
  int after_context,
  bool classify_definitions,
);

/// Offset a pointer by `byte_offset` bytes (FFI array iteration helper).
/// Returns null if `base` is null.
///
/// ## Safety
/// The resulting pointer must be within the bounds of the original allocation.
@ffi.Native<
  ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.UintPtr)
>()
external ffi.Pointer<ffi.Void> fff_ptr_offset(
  ffi.Pointer<ffi.Void> base,
  int byte_offset,
);

/// Refresh git status cache.
///
/// ## Safety
/// `fff_handle` must be a valid instance pointer from `fff_create_instance`.
@ffi.Native<ffi.Pointer<FffResult> Function(ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<FffResult> fff_refresh_git_status(
  ffi.Pointer<ffi.Void> fff_handle,
);

/// Restart indexing in a new directory.
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`.
/// * `new_path` must be a valid null-terminated UTF-8 string.
@ffi.Native<
  ffi.Pointer<FffResult> Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<FffResult> fff_restart_index(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> new_path,
);

/// Returns the operation error message, or null when there is no error or `result` is null.
///
/// Do not free the returned pointer. It remains valid until `fff_free_result` is called.
///
/// ## Safety
/// `result` must be a valid `FffResult` pointer or null.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffResult>)>()
external ffi.Pointer<ffi.Char> fff_result_get_error(
  ffi.Pointer<FffResult> result,
);

/// Returns the result payload handle, or null if `result` is null.
///
/// ## Safety
/// `result` must be a valid `FffResult` pointer or null.
@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<FffResult>)>()
external ffi.Pointer<ffi.Void> fff_result_get_handle(
  ffi.Pointer<FffResult> result,
);

/// Returns the result integer payload. Returns `0` if `result` is null.
///
/// ## Safety
/// `result` must be a valid `FffResult` pointer or null.
@ffi.Native<ffi.Int64 Function(ffi.Pointer<FffResult>)>()
external int fff_result_get_int_value(ffi.Pointer<FffResult> result);

/// Returns whether the operation completed successfully. Returns `false` if `result` is null.
///
/// ## Safety
/// `result` must be a valid `FffResult` pointer or null.
@ffi.Native<ffi.Bool Function(ffi.Pointer<FffResult>)>()
external bool fff_result_get_success(ffi.Pointer<FffResult> result);

/// Trigger a rescan of the file index.
///
/// ## Safety
/// `fff_handle` must be a valid instance pointer from `fff_create_instance`.
@ffi.Native<ffi.Pointer<FffResult> Function(ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<FffResult> fff_scan_files(
  ffi.Pointer<ffi.Void> fff_handle,
);

/// Perform fuzzy search on indexed files.
///
/// `current_file` deprioritizes the currently open file (NULL/empty to skip).
/// Zero picks the default: `max_threads` auto, `page_size` 100,
/// `combo_boost_multiplier` 100, `min_combo_count` 3.
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`.
/// * `query` and `current_file` must be valid null-terminated UTF-8 strings or NULL.
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint32,
  )
>()
external ffi.Pointer<FffResult> fff_search(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> query,
  ffi.Pointer<ffi.Char> current_file,
  int max_threads,
  int page_index,
  int page_size,
  int combo_boost_multiplier,
  int min_combo_count,
);

/// Perform fuzzy search on indexed directories.
///
/// `current_file` is used for distance scoring (NULL/empty to skip).
/// Zero picks the default: `max_threads` auto, `page_size` 100.
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`.
/// * `query` and `current_file` must be valid null-terminated UTF-8 strings or NULL.
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external ffi.Pointer<FffResult> fff_search_directories(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> query,
  ffi.Pointer<ffi.Char> current_file,
  int max_threads,
  int page_index,
  int page_size,
);

/// Perform a mixed fuzzy search across both files and directories.
///
/// Returns one flat list interleaved by descending total score; each item's
/// `item_type` is 0 = file, 1 = directory. Parameters as in [`fff_search`].
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`.
/// * `query` and `current_file` must be valid null-terminated UTF-8 strings or NULL.
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint32,
  )
>()
external ffi.Pointer<FffResult> fff_search_mixed(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> query,
  ffi.Pointer<ffi.Char> current_file,
  int max_threads,
  int page_index,
  int page_size,
  int combo_boost_multiplier,
  int min_combo_count,
);

/// Number of items in the result; `0` if `r` is null.
///
/// ## Safety
/// `r` must be a valid `FffSearchResult` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffSearchResult>)>()
external int fff_search_result_get_count(ffi.Pointer<FffSearchResult> r);

/// Pointer to the `index`-th `FffFileItem`; null if `result` is null or
/// `index >= count`. Valid until the search result is freed.
///
/// ## Safety
/// `result` must be a valid `FffSearchResult` pointer from `fff_search`.
@ffi.Native<
  ffi.Pointer<FffFileItem> Function(ffi.Pointer<FffSearchResult>, ffi.Uint32)
>()
external ffi.Pointer<FffFileItem> fff_search_result_get_item(
  ffi.Pointer<FffSearchResult> result,
  int index,
);

/// Pointer to the `index`-th `FffScore`; null if `result` is null or
/// `index >= count`. Valid until the search result is freed.
///
/// ## Safety
/// `result` must be a valid `FffSearchResult` pointer from `fff_search`.
@ffi.Native<
  ffi.Pointer<FffScore> Function(ffi.Pointer<FffSearchResult>, ffi.Uint32)
>()
external ffi.Pointer<FffScore> fff_search_result_get_score(
  ffi.Pointer<FffSearchResult> result,
  int index,
);

/// Total number of indexed files considered during search; `0` if `r` is null.
///
/// ## Safety
/// `r` must be a valid `FffSearchResult` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffSearchResult>)>()
external int fff_search_result_get_total_files(ffi.Pointer<FffSearchResult> r);

/// Total number of files that matched before truncation to the page size; `0` if `r` is null.
///
/// ## Safety
/// `r` must be a valid `FffSearchResult` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffSearchResult>)>()
external int fff_search_result_get_total_matched(
  ffi.Pointer<FffSearchResult> r,
);

/// Register the instance-wide watch callback used by all `fff_watch`
/// subscriptions; call before the first `fff_watch`, calling again replaces it.
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`.
/// * `callback` must remain callable until fff_unwatch called
/// `fff_destroy(fff_handle)` returns.
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    FffWatchCallback,
    ffi.Pointer<ffi.Void>,
  )
>()
external ffi.Pointer<FffResult> fff_set_watch_callback(
  ffi.Pointer<ffi.Void> fff_handle,
  FffWatchCallback callback,
  ffi.Pointer<ffi.Void> user_data,
);

/// Track query completion for smart suggestions.
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`.
/// * `query` and `file_path` must be valid null-terminated UTF-8 strings.
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<FffResult> fff_track_query(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> query,
  ffi.Pointer<ffi.Char> file_path,
);

/// Remove a watch subscription. `int_value` = 1 if the id existed, 0 otherwise.
///
/// ## Safety
/// `fff_handle` must be a valid instance pointer from `fff_create_instance`.
@ffi.Native<
  ffi.Pointer<FffResult> Function(ffi.Pointer<ffi.Void>, ffi.Uint64)
>()
external ffi.Pointer<FffResult> fff_unwatch(
  ffi.Pointer<ffi.Void> fff_handle,
  int watch_id,
);

/// Wait for initial scan to complete.
///
/// ## Safety
/// `fff_handle` must be a valid instance pointer from `fff_create_instance`.
@ffi.Native<
  ffi.Pointer<FffResult> Function(ffi.Pointer<ffi.Void>, ffi.Uint64)
>()
external ffi.Pointer<FffResult> fff_wait_for_scan(
  ffi.Pointer<ffi.Void> fff_handle,
  int timeout_ms,
);

/// Wait for the background file watcher to be ready.
///
/// ## Safety
/// `fff_handle` must be a valid instance pointer from `fff_create_instance`.
@ffi.Native<
  ffi.Pointer<FffResult> Function(ffi.Pointer<ffi.Void>, ffi.Uint64)
>()
external ffi.Pointer<FffResult> fff_wait_for_watcher(
  ffi.Pointer<ffi.Void> fff_handle,
  int timeout_ms,
);

/// Subscribe to filesystem changes, delivered through the instance callback
/// registered by `fff_set_watch_callback`.
///
/// Returns the watch id, pass it to `fff_unwatch` to stop.
///
/// `pattern` if non `NULL` can be wildcard pattern, absolute, or relative path
/// that will be used to filter the events triggering exact subscription.
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`.
/// * `pattern` must be NULL or valid null-terminated UTF-8.
/// * `opts` must be NULL or a valid `FffWatchOptions` pointer.
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<FffWatchOptions>,
  )
>()
external ffi.Pointer<FffResult> fff_watch(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> pattern,
  ffi.Pointer<FffWatchOptions> opts,
);

/// [`fff_watch`] adapter with flattened options, for FFI libraries that cannot
/// marshal pointer arrays inside structs (e.g. Node's `ffi-rs`).
///
/// ## Safety
/// * `fff_handle` must be a valid instance pointer from `fff_create_instance`.
/// * `pattern` must be NULL (watch everything) or valid null-terminated UTF-8.
/// * `ignore` must be NULL or point to `ignore_count` valid C strings.
@ffi.Native<
  ffi.Pointer<FffResult> Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Uint32,
  )
>()
external ffi.Pointer<FffResult> fff_watch_args(
  ffi.Pointer<ffi.Void> fff_handle,
  ffi.Pointer<ffi.Char> pattern,
  ffi.Pointer<ffi.Pointer<ffi.Char>> ignore,
  int ignore_count,
);

/// Number of events in a batch, 0 if `batch` is null.
///
/// ## Safety
/// `batch` must be a valid `FffWatchEventBatch` pointer or null.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<FffWatchEventBatch>)>()
external int fff_watch_events_count(ffi.Pointer<FffWatchEventBatch> batch);

/// Pre-rename path of event `index`, null unless its kind is 4 (renamed).
/// Owned by the batch; do not free separately.
///
/// ## Safety
/// `batch` must be a valid `FffWatchEventBatch` pointer or null.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffWatchEventBatch>, ffi.Uint32)
>()
external ffi.Pointer<ffi.Char> fff_watch_events_get_from_path(
  ffi.Pointer<FffWatchEventBatch> batch,
  int index,
);

/// Kind of event `index` (0 = created, 1 = modified, 2 = removed, 3 = rescan,
/// 4 = renamed).
/// 3 (rescan aka "re-stat something" kind) returned when OS based buffer
/// has been overflown and some events might be loss. Paths will contain a list of
/// directories that needs to be rescanned to ensure consistency.
/// 4 reports a move: `path` is the destination and
/// `fff_watch_events_get_from_path` yields the source.
///
/// ## Safety
/// `batch` must be a valid `FffWatchEventBatch` pointer or null.
@ffi.Native<ffi.Uint8 Function(ffi.Pointer<FffWatchEventBatch>, ffi.Uint32)>()
external int fff_watch_events_get_kind(
  ffi.Pointer<FffWatchEventBatch> batch,
  int index,
);

/// Absolute path of event `index`, will be null when out of bounds
///
/// ## Safety
/// `batch` must be a valid `FffWatchEventBatch` pointer or null.
@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<FffWatchEventBatch>, ffi.Uint32)
>()
external ffi.Pointer<ffi.Char> fff_watch_events_get_path(
  ffi.Pointer<FffWatchEventBatch> batch,
  int index,
);

const int FFF_CREATE_OPTIONS_VERSION = 2;

const int FFF_WATCH_OPTIONS_VERSION = 1;

/// Options for `fff_create_instance_with`.
///
/// Versioned struct: the layout is stable across releases, new fields are
/// only appended.
final class FffCreateOptions extends ffi.Struct {
  /// Set to [`FFF_CREATE_OPTIONS_VERSION`] when allocating; tells the
  /// library which trailing fields are populated.
  @ffi.Uint32()
  external int version;

  /// Directory to index (required, non-NULL).
  external ffi.Pointer<ffi.Char> base_path;

  /// Frecency LMDB database path. NULL/empty to skip frecency tracking.
  external ffi.Pointer<ffi.Char> frecency_db_path;

  /// Query history LMDB database path. NULL/empty to skip query tracking.
  external ffi.Pointer<ffi.Char> history_db_path;

  /// Pre-populate mmap caches for top-frecency files after the initial scan.
  @ffi.Bool()
  external bool enable_mmap_cache;

  /// Build content index after the initial scan for faster grep.
  @ffi.Bool()
  external bool enable_content_indexing;

  /// Start a background file-system watcher for live updates.
  @ffi.Bool()
  external bool watch;

  /// Enable AI-agent optimizations.
  @ffi.Bool()
  external bool ai_mode;

  /// Tracing log file path. NULL/empty to skip log init.
  external ffi.Pointer<ffi.Char> log_file_path;

  /// Log level: `"trace" | "debug" | "info" | "warn" | "error"`.
  /// NULL/empty defaults to `"info"`. Ignored when `log_file_path` is unset.
  external ffi.Pointer<ffi.Char> log_level;

  /// Content cache file-count cap. 0 = auto.
  @ffi.Uint64()
  external int cache_budget_max_files;

  /// Content cache byte cap. 0 = auto.
  @ffi.Uint64()
  external int cache_budget_max_bytes;

  /// Per-file byte cap inside the content cache. 0 = auto.
  @ffi.Uint64()
  external int cache_budget_max_file_size;

  /// Allow indexing the filesystem root (`/`). Off by default: root is rarely
  /// intended and floods the watcher with churn.
  @ffi.Bool()
  external bool enable_fs_root_scanning;

  /// Allow indexing the user's home directory. Same trade-off as `enable_fs_root_scanning`.
  @ffi.Bool()
  external bool enable_home_dir_scanning;

  /// Follow symlinks during scan and watcher walks. Off by default: without
  /// external loop protection cyclic symlinks can wedge the watcher.
  @ffi.Bool()
  external bool follow_symlinks;

  static ffi.Pointer<FffCreateOptions> $allocate(
    ffi.Allocator $allocator, {
    required int version,
    required ffi.Pointer<ffi.Char> base_path,
    required ffi.Pointer<ffi.Char> frecency_db_path,
    required ffi.Pointer<ffi.Char> history_db_path,
    required bool enable_mmap_cache,
    required bool enable_content_indexing,
    required bool watch,
    required bool ai_mode,
    required ffi.Pointer<ffi.Char> log_file_path,
    required ffi.Pointer<ffi.Char> log_level,
    required int cache_budget_max_files,
    required int cache_budget_max_bytes,
    required int cache_budget_max_file_size,
    required bool enable_fs_root_scanning,
    required bool enable_home_dir_scanning,
    required bool follow_symlinks,
  }) => $allocator<FffCreateOptions>()
    ..ref.version = version
    ..ref.base_path = base_path
    ..ref.frecency_db_path = frecency_db_path
    ..ref.history_db_path = history_db_path
    ..ref.enable_mmap_cache = enable_mmap_cache
    ..ref.enable_content_indexing = enable_content_indexing
    ..ref.watch = watch
    ..ref.ai_mode = ai_mode
    ..ref.log_file_path = log_file_path
    ..ref.log_level = log_level
    ..ref.cache_budget_max_files = cache_budget_max_files
    ..ref.cache_budget_max_bytes = cache_budget_max_bytes
    ..ref.cache_budget_max_file_size = cache_budget_max_file_size
    ..ref.enable_fs_root_scanning = enable_fs_root_scanning
    ..ref.enable_home_dir_scanning = enable_home_dir_scanning
    ..ref.follow_symlinks = follow_symlinks;
}

/// A directory item returned by `fff_search_directories`. Strings are owned by
/// the parent `FffDirSearchResult`; free everything with `fff_free_dir_search_result`.
final class FffDirItem extends ffi.Struct {
  external ffi.Pointer<ffi.Char> relative_path;

  external ffi.Pointer<ffi.Char> dir_name;

  @ffi.Int32()
  external int max_access_frecency;

  static ffi.Pointer<FffDirItem> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> relative_path,
    required ffi.Pointer<ffi.Char> dir_name,
    required int max_access_frecency,
  }) => $allocator<FffDirItem>()
    ..ref.relative_path = relative_path
    ..ref.dir_name = dir_name
    ..ref.max_access_frecency = max_access_frecency;
}

/// Directory search result returned by `fff_search_directories`;
/// free with `fff_free_dir_search_result`.
final class FffDirSearchResult extends ffi.Struct {
  /// Heap array of `FffDirItem` (length = `count`).
  external ffi.Pointer<FffDirItem> items;

  /// Heap array of `FffScore` (length = `count`).
  external ffi.Pointer<FffScore> scores;

  /// Number of items/scores in the arrays.
  @ffi.Uint32()
  external int count;

  /// Total number of directories that matched the query.
  @ffi.Uint32()
  external int total_matched;

  /// Total number of indexed directories.
  @ffi.Uint32()
  external int total_dirs;

  static ffi.Pointer<FffDirSearchResult> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<FffDirItem> items,
    required ffi.Pointer<FffScore> scores,
    required int count,
    required int total_matched,
    required int total_dirs,
  }) => $allocator<FffDirSearchResult>()
    ..ref.items = items
    ..ref.scores = scores
    ..ref.count = count
    ..ref.total_matched = total_matched
    ..ref.total_dirs = total_dirs;
}

/// A file item returned by `fff_search`. Strings are owned by the parent
/// `FffSearchResult`; free everything with `fff_free_search_result`.
final class FffFileItem extends ffi.Struct {
  external ffi.Pointer<ffi.Char> relative_path;

  external ffi.Pointer<ffi.Char> file_name;

  external ffi.Pointer<ffi.Char> git_status;

  @ffi.Uint64()
  external int size;

  @ffi.Uint64()
  external int modified;

  @ffi.Int64()
  external int access_frecency_score;

  @ffi.Int64()
  external int modification_frecency_score;

  @ffi.Int64()
  external int total_frecency_score;

  @ffi.Bool()
  external bool is_binary;

  static ffi.Pointer<FffFileItem> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> relative_path,
    required ffi.Pointer<ffi.Char> file_name,
    required ffi.Pointer<ffi.Char> git_status,
    required int size,
    required int modified,
    required int access_frecency_score,
    required int modification_frecency_score,
    required int total_frecency_score,
    required bool is_binary,
  }) => $allocator<FffFileItem>()
    ..ref.relative_path = relative_path
    ..ref.file_name = file_name
    ..ref.git_status = git_status
    ..ref.size = size
    ..ref.modified = modified
    ..ref.access_frecency_score = access_frecency_score
    ..ref.modification_frecency_score = modification_frecency_score
    ..ref.total_frecency_score = total_frecency_score
    ..ref.is_binary = is_binary;
}

/// A single grep match with file and line information. Strings and arrays are
/// owned by the parent `FffGrepResult`; free everything with `fff_free_grep_result`.
final class FffGrepMatch extends ffi.Struct {
  external ffi.Pointer<ffi.Char> relative_path;

  external ffi.Pointer<ffi.Char> file_name;

  external ffi.Pointer<ffi.Char> git_status;

  external ffi.Pointer<ffi.Char> line_content;

  external ffi.Pointer<FffMatchRange> match_ranges;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> context_before;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> context_after;

  @ffi.Uint64()
  external int size;

  @ffi.Uint64()
  external int modified;

  @ffi.Int64()
  external int total_frecency_score;

  @ffi.Int64()
  external int access_frecency_score;

  @ffi.Int64()
  external int modification_frecency_score;

  @ffi.Uint64()
  external int line_number;

  @ffi.Uint64()
  external int byte_offset;

  @ffi.Uint32()
  external int col;

  @ffi.Uint32()
  external int match_ranges_count;

  @ffi.Uint32()
  external int context_before_count;

  @ffi.Uint32()
  external int context_after_count;

  @ffi.Uint16()
  external int fuzzy_score;

  @ffi.Bool()
  external bool has_fuzzy_score;

  @ffi.Bool()
  external bool is_binary;

  @ffi.Bool()
  external bool is_definition;

  static ffi.Pointer<FffGrepMatch> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> relative_path,
    required ffi.Pointer<ffi.Char> file_name,
    required ffi.Pointer<ffi.Char> git_status,
    required ffi.Pointer<ffi.Char> line_content,
    required ffi.Pointer<FffMatchRange> match_ranges,
    required ffi.Pointer<ffi.Pointer<ffi.Char>> context_before,
    required ffi.Pointer<ffi.Pointer<ffi.Char>> context_after,
    required int size,
    required int modified,
    required int total_frecency_score,
    required int access_frecency_score,
    required int modification_frecency_score,
    required int line_number,
    required int byte_offset,
    required int col,
    required int match_ranges_count,
    required int context_before_count,
    required int context_after_count,
    required int fuzzy_score,
    required bool has_fuzzy_score,
    required bool is_binary,
    required bool is_definition,
  }) => $allocator<FffGrepMatch>()
    ..ref.relative_path = relative_path
    ..ref.file_name = file_name
    ..ref.git_status = git_status
    ..ref.line_content = line_content
    ..ref.match_ranges = match_ranges
    ..ref.context_before = context_before
    ..ref.context_after = context_after
    ..ref.size = size
    ..ref.modified = modified
    ..ref.total_frecency_score = total_frecency_score
    ..ref.access_frecency_score = access_frecency_score
    ..ref.modification_frecency_score = modification_frecency_score
    ..ref.line_number = line_number
    ..ref.byte_offset = byte_offset
    ..ref.col = col
    ..ref.match_ranges_count = match_ranges_count
    ..ref.context_before_count = context_before_count
    ..ref.context_after_count = context_after_count
    ..ref.fuzzy_score = fuzzy_score
    ..ref.has_fuzzy_score = has_fuzzy_score
    ..ref.is_binary = is_binary
    ..ref.is_definition = is_definition;
}

/// Grep result returned by `fff_live_grep` and `fff_multi_grep`;
/// free with `fff_free_grep_result`.
final class FffGrepResult extends ffi.Struct {
  /// Heap array of `FffGrepMatch` (length = `count`).
  external ffi.Pointer<FffGrepMatch> items;

  /// Number of matches in the `items` array.
  @ffi.Uint32()
  external int count;

  /// Total number of matches (always equal to `count`).
  @ffi.Uint32()
  external int total_matched;

  /// Number of files actually opened and searched in this call.
  @ffi.Uint32()
  external int total_files_searched;

  /// Total number of indexed files (before any filtering).
  @ffi.Uint32()
  external int total_files;

  /// Number of files eligible for search after filtering.
  @ffi.Uint32()
  external int filtered_file_count;

  /// File offset for the next page. 0 if all files have been searched.
  @ffi.Uint32()
  external int next_file_offset;

  /// Regex compilation error when falling back to literal matching. Null if none.
  external ffi.Pointer<ffi.Char> regex_fallback_error;

  static ffi.Pointer<FffGrepResult> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<FffGrepMatch> items,
    required int count,
    required int total_matched,
    required int total_files_searched,
    required int total_files,
    required int filtered_file_count,
    required int next_file_offset,
    required ffi.Pointer<ffi.Char> regex_fallback_error,
  }) => $allocator<FffGrepResult>()
    ..ref.items = items
    ..ref.count = count
    ..ref.total_matched = total_matched
    ..ref.total_files_searched = total_files_searched
    ..ref.total_files = total_files
    ..ref.filtered_file_count = filtered_file_count
    ..ref.next_file_offset = next_file_offset
    ..ref.regex_fallback_error = regex_fallback_error;
}

/// Location parsed from a query string (e.g. `"file.ts:42:10"`). `tag`:
/// 0 = none, 1 = line, 2 = position (`line` + `col`),
/// 3 = range (`line`/`col` = start, `end_line`/`end_col` = end).
final class FffLocation extends ffi.Struct {
  @ffi.Uint8()
  external int tag;

  @ffi.Int32()
  external int line;

  @ffi.Int32()
  external int col;

  @ffi.Int32()
  external int end_line;

  @ffi.Int32()
  external int end_col;

  static ffi.Pointer<FffLocation> $allocate(
    ffi.Allocator $allocator, {
    required int tag,
    required int line,
    required int col,
    required int end_line,
    required int end_col,
  }) => $allocator<FffLocation>()
    ..ref.tag = tag
    ..ref.line = line
    ..ref.col = col
    ..ref.end_line = end_line
    ..ref.end_col = end_col;
}

/// A byte range within a matched line, used for highlighting.
final class FffMatchRange extends ffi.Struct {
  @ffi.Uint32()
  external int start;

  @ffi.Uint32()
  external int end;

  static ffi.Pointer<FffMatchRange> $allocate(
    ffi.Allocator $allocator, {
    required int start,
    required int end,
  }) => $allocator<FffMatchRange>()
    ..ref.start = start
    ..ref.end = end;
}

/// A single item in a mixed (files + directories) search result.
/// `item_type`: 0 = file, 1 = directory. Strings are owned by the parent
/// `FffMixedSearchResult`.
final class FffMixedItem extends ffi.Struct {
  /// 0 = file, 1 = directory.
  @ffi.Uint8()
  external int item_type;

  external ffi.Pointer<ffi.Char> relative_path;

  /// Filename for files, last directory segment for directories.
  external ffi.Pointer<ffi.Char> display_name;

  external ffi.Pointer<ffi.Char> git_status;

  @ffi.Uint64()
  external int size;

  @ffi.Uint64()
  external int modified;

  /// Access frecency for files; max among immediate children for directories.
  @ffi.Int64()
  external int access_frecency_score;

  /// Always 0 for directories
  @ffi.Int64()
  external int modification_frecency_score;

  /// Always 0 for directories
  @ffi.Int64()
  external int total_frecency_score;

  /// Always 0 for directories
  @ffi.Bool()
  external bool is_binary;

  static ffi.Pointer<FffMixedItem> $allocate(
    ffi.Allocator $allocator, {
    required int item_type,
    required ffi.Pointer<ffi.Char> relative_path,
    required ffi.Pointer<ffi.Char> display_name,
    required ffi.Pointer<ffi.Char> git_status,
    required int size,
    required int modified,
    required int access_frecency_score,
    required int modification_frecency_score,
    required int total_frecency_score,
    required bool is_binary,
  }) => $allocator<FffMixedItem>()
    ..ref.item_type = item_type
    ..ref.relative_path = relative_path
    ..ref.display_name = display_name
    ..ref.git_status = git_status
    ..ref.size = size
    ..ref.modified = modified
    ..ref.access_frecency_score = access_frecency_score
    ..ref.modification_frecency_score = modification_frecency_score
    ..ref.total_frecency_score = total_frecency_score
    ..ref.is_binary = is_binary;
}

/// Mixed search result returned by `fff_search_mixed`
/// free with `fff_free_mixed_search_result`.
final class FffMixedSearchResult extends ffi.Struct {
  /// Heap array of `FffMixedItem` (length = `count`).
  external ffi.Pointer<FffMixedItem> items;

  /// Heap array of `FffScore` (length = `count`).
  external ffi.Pointer<FffScore> scores;

  /// Number of items/scores in the arrays.
  @ffi.Uint32()
  external int count;

  /// Total number of items (files + dirs) that matched the query.
  @ffi.Uint32()
  external int total_matched;

  /// Total number of indexed files.
  @ffi.Uint32()
  external int total_files;

  /// Total number of indexed directories.
  @ffi.Uint32()
  external int total_dirs;

  /// Location parsed from the query string.
  external FffLocation location;
}

/// Result envelope returned by all `fff_*` functions.
///
/// Heap-allocated. The caller must free it with `fff_free_result`. Calling `fff_free_result`
/// **does not** deallocate the underlying `handle` pointer. It needs to be cleaned separately.
/// see (`fff_destroy`, `fff_free_search_result`, `fff_free_grep_result`, `fff_free_string`, etc.).
///
/// Depending on the function, the payload is delivered through different fields:
///
/// | Function                   | Payload field | Type                          |
/// |----------------------------|---------------|-------------------------------|
/// | `fff_create_instance`      | `handle`      | opaque instance pointer       |
/// | `fff_search`               | `handle`      | `*mut FffSearchResult`        |
/// | `fff_live_grep`            | `handle`      | `*mut FffGrepResult`          |
/// | `fff_multi_grep`           | `handle`      | `*mut FffGrepResult`          |
/// | `fff_get_scan_progress`    | `handle`      | `*mut FffScanProgress`        |
/// | `fff_health_check`         | `handle`      | `*mut c_char` (JSON string)   |
/// | `fff_get_historical_query` | `handle`      | `*mut c_char` (string or null)|
/// | `fff_wait_for_scan`        | `int_value`   | 1 = completed, 0 = timed out  |
/// | `fff_track_query`          | `int_value`   | 1 = success, 0 = failure      |
/// | `fff_refresh_git_status`   | `int_value`   | number of files updated       |
/// | `fff_scan_files`           | (none)        | success flag only             |
/// | `fff_restart_index`        | (none)        | success flag only             |
///
/// On failure, `success` is false and `error` contains the message.
final class FffResult extends ffi.Struct {
  /// Whether the operation succeeded.
  @ffi.Bool()
  external bool success;

  /// Error message on failure. Null on success.
  external ffi.Pointer<ffi.Char> error;

  /// Opaque pointer payload. May be null.
  external ffi.Pointer<ffi.Void> handle;

  /// Integer payload for simple return values (bool as 0/1, counts, etc.).
  @ffi.Int64()
  external int int_value;

  static ffi.Pointer<FffResult> $allocate(
    ffi.Allocator $allocator, {
    required bool success,
    required ffi.Pointer<ffi.Char> error,
    required ffi.Pointer<ffi.Void> handle,
    required int int_value,
  }) => $allocator<FffResult>()
    ..ref.success = success
    ..ref.error = error
    ..ref.handle = handle
    ..ref.int_value = int_value;
}

/// Scan progress returned by `fff_get_scan_progress`.
/// The caller must free this with `fff_free_scan_progress`.
final class FffScanProgress extends ffi.Struct {
  @ffi.Uint64()
  external int scanned_files_count;

  @ffi.Bool()
  external bool is_scanning;

  @ffi.Bool()
  external bool is_watcher_ready;

  @ffi.Bool()
  external bool is_warmup_complete;

  static ffi.Pointer<FffScanProgress> $allocate(
    ffi.Allocator $allocator, {
    required int scanned_files_count,
    required bool is_scanning,
    required bool is_watcher_ready,
    required bool is_warmup_complete,
  }) => $allocator<FffScanProgress>()
    ..ref.scanned_files_count = scanned_files_count
    ..ref.is_scanning = is_scanning
    ..ref.is_watcher_ready = is_watcher_ready
    ..ref.is_warmup_complete = is_warmup_complete;
}

/// Score breakdown for a search result.
final class FffScore extends ffi.Struct {
  @ffi.Int32()
  external int total;

  @ffi.Int32()
  external int base_score;

  @ffi.Int32()
  external int filename_bonus;

  @ffi.Int32()
  external int special_filename_bonus;

  @ffi.Int32()
  external int frecency_boost;

  @ffi.Int32()
  external int distance_penalty;

  @ffi.Int32()
  external int current_file_penalty;

  @ffi.Int32()
  external int combo_match_boost;

  @ffi.Int32()
  external int path_alignment_bonus;

  @ffi.Bool()
  external bool exact_match;

  external ffi.Pointer<ffi.Char> match_type;

  static ffi.Pointer<FffScore> $allocate(
    ffi.Allocator $allocator, {
    required int total,
    required int base_score,
    required int filename_bonus,
    required int special_filename_bonus,
    required int frecency_boost,
    required int distance_penalty,
    required int current_file_penalty,
    required int combo_match_boost,
    required int path_alignment_bonus,
    required bool exact_match,
    required ffi.Pointer<ffi.Char> match_type,
  }) => $allocator<FffScore>()
    ..ref.total = total
    ..ref.base_score = base_score
    ..ref.filename_bonus = filename_bonus
    ..ref.special_filename_bonus = special_filename_bonus
    ..ref.frecency_boost = frecency_boost
    ..ref.distance_penalty = distance_penalty
    ..ref.current_file_penalty = current_file_penalty
    ..ref.combo_match_boost = combo_match_boost
    ..ref.path_alignment_bonus = path_alignment_bonus
    ..ref.exact_match = exact_match
    ..ref.match_type = match_type;
}

/// Search result returned by `fff_search`; free with `fff_free_search_result`.
final class FffSearchResult extends ffi.Struct {
  /// Heap array of `FffFileItem` (length = `count`).
  external ffi.Pointer<FffFileItem> items;

  /// Heap array of `FffScore` (length = `count`).
  external ffi.Pointer<FffScore> scores;

  /// Number of items/scores in the arrays.
  @ffi.Uint32()
  external int count;

  /// Total number of files that matched the query.
  @ffi.Uint32()
  external int total_matched;

  /// Total number of indexed files.
  @ffi.Uint32()
  external int total_files;

  /// Location parsed from the query string.
  external FffLocation location;
}

/// Instance-wide callback invoked with `(watch_id, batch)` for every `fff_watch`
/// subscription. The callee owns and frees `batch` via `fff_free_watch_events`.
typedef FffWatchCallback =
    ffi.Pointer<ffi.NativeFunction<FffWatchCallbackFunction>>;
typedef FffWatchCallbackFunction = ffi.Void Function(
  ffi.Uint64 watch_id,
  ffi.Pointer<FffWatchEventBatch> batch,
  ffi.Pointer<ffi.Void> user_data,
);
typedef DartFffWatchCallbackFunction = void Function(
  int watch_id,
  ffi.Pointer<FffWatchEventBatch> batch,
  ffi.Pointer<ffi.Void> user_data,
);

/// A single watch event. `kind`: 0 = created, 1 = modified, 2 = removed,
/// 3 = rescan (events were lost; re-stat what you care about),
/// 4 = renamed (`path` is the destination; read the source with
/// `fff_watch_events_get_from_path`).
///
/// Layout is frozen: this is an array element, so growing it would change the
/// stride every existing binding compiled against.
final class FffWatchEvent extends ffi.Struct {
  /// Absolute path (heap C string owned by the parent batch).
  external ffi.Pointer<ffi.Char> path;

  @ffi.Uint8()
  external int kind;

  static ffi.Pointer<FffWatchEvent> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> path,
    required int kind,
  }) => $allocator<FffWatchEvent>()
    ..ref.path = path
    ..ref.kind = kind;
}

/// A batch of watch events. Free with `fff_free_watch_events`.
/// Versioned by append only: existing field offsets never move.
final class FffWatchEventBatch extends ffi.Struct {
  external ffi.Pointer<FffWatchEvent> events;

  @ffi.Uint32()
  external int count;

  /// Parallel to `events`, `count` long: the pre-rename path for entries
  /// with `kind == 4`, null for every other entry. Null when the batch holds
  /// no renames at all.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> rename_sources;

  static ffi.Pointer<FffWatchEventBatch> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<FffWatchEvent> events,
    required int count,
    required ffi.Pointer<ffi.Pointer<ffi.Char>> rename_sources,
  }) => $allocator<FffWatchEventBatch>()
    ..ref.events = events
    ..ref.count = count
    ..ref.rename_sources = rename_sources;
}

/// Options for `fff_watch`. Versioned: new fields are only appended.
final class FffWatchOptions extends ffi.Struct {
  /// Set to [`FFF_WATCH_OPTIONS_VERSION`] when allocating.
  @ffi.Uint32()
  external int version;

  /// Per-subscription excludes (parcel-watcher style): entries with wildcards
  /// are base-relative globs, entries without are path prefixes. NULL when
  /// `ignore_count` is 0.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> ignore;

  @ffi.Uint32()
  external int ignore_count;

  static ffi.Pointer<FffWatchOptions> $allocate(
    ffi.Allocator $allocator, {
    required int version,
    required ffi.Pointer<ffi.Pointer<ffi.Char>> ignore,
    required int ignore_count,
  }) => $allocator<FffWatchOptions>()
    ..ref.version = version
    ..ref.ignore = ignore
    ..ref.ignore_count = ignore_count;
}
