import 'dart:io';

import 'package:crypto/crypto.dart';

/// Generates the manifest from this package's own release binaries.
///
/// Download the `fff-*` assets from an elias8/fff_dart release into one
/// directory, then pass that directory and its release tag. All supported
/// target binaries must be present before the manifest is changed.
void main(List<String> args) {
  if (args.length != 2) {
    throw ArgumentError(
      'Usage: dart tool/generate_binary_hash.dart <artifacts-directory> '
      '<fff_dart-release-tag>',
    );
  }
  final directory = Directory(args[0]);
  final tag = args[1];
  if (!directory.existsSync()) {
    throw ArgumentError.value(directory.path, 'artifacts-directory');
  }
  if (!RegExp(r'^fff_dart-v\d+\.\d+\.\d+$').hasMatch(tag)) {
    throw ArgumentError.value(tag, 'fff_dart-release-tag');
  }
  const names = [
    'fff-aarch64-apple-darwin.dylib',
    'fff-aarch64-linux-android.so',
    'fff-aarch64-pc-windows-msvc.dll',
    'fff-aarch64-unknown-linux-gnu.so',
    'fff-aarch64-unknown-linux-musl.so',
    'fff-x86_64-apple-darwin.dylib',
    'fff-x86_64-pc-windows-msvc.dll',
    'fff-x86_64-unknown-linux-gnu.so',
    'fff-x86_64-unknown-linux-musl.so',
  ];
  final hashes = <String, String>{};
  for (final name in names) {
    final file = File.fromUri(directory.uri.resolve(name));
    if (!file.existsSync()) {
      throw StateError('Missing release artifact: ${file.path}');
    }
    hashes[name] = sha256.convert(file.readAsBytesSync()).toString();
  }

  final output = StringBuffer()
    ..writeln('// Generated by tool/generate_binary_hash.dart.')
    ..writeln("const releaseTag = '$tag';")
    ..writeln()
    ..writeln('const assetHashes = <String, String>{');
  for (final entry in hashes.entries) {
    output.writeln("  '${entry.key}':");
    output.writeln("      '${entry.value}',");
  }
  output.writeln('};');
  File('lib/src/hook/asset_hashes.dart').writeAsStringSync(output.toString());
  stdout.writeln('Wrote ${hashes.length} FFF hashes for $tag');
}
